# $Id: Makefile 10897 2012-09-20 15:39:44Z djcinsb $
# GmatFunction makefile 
#
# This file calls make on the base folder.

all: 
	cd base; make all

rebuild: 
	cd base; make clean; make all

clean:
	cd base; make clean
